//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.12 at 08:19:09 AM CEST 
//


package consumesoap.soapclient.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for addSignerIdToSignerId complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="addSignerIdToSignerId"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="domainName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="existentSignerId" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}signerIdDTO"/&gt;
 *         &lt;element name="newSignerId" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}signerIdDTO"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addSignerIdToSignerId", propOrder = {
    "domainName",
    "existentSignerId",
    "newSignerId"
})
public class AddSignerIdToSignerId {

    @XmlElement(required = true)
    protected String domainName;
    @XmlElement(required = true)
    protected SignerIdDTO existentSignerId;
    @XmlElement(required = true)
    protected SignerIdDTO newSignerId;

    /**
     * Gets the value of the domainName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomainName() {
        return domainName;
    }

    /**
     * Sets the value of the domainName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomainName(String value) {
        this.domainName = value;
    }

    /**
     * Gets the value of the existentSignerId property.
     * 
     * @return
     *     possible object is
     *     {@link SignerIdDTO }
     *     
     */
    public SignerIdDTO getExistentSignerId() {
        return existentSignerId;
    }

    /**
     * Sets the value of the existentSignerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignerIdDTO }
     *     
     */
    public void setExistentSignerId(SignerIdDTO value) {
        this.existentSignerId = value;
    }

    /**
     * Gets the value of the newSignerId property.
     * 
     * @return
     *     possible object is
     *     {@link SignerIdDTO }
     *     
     */
    public SignerIdDTO getNewSignerId() {
        return newSignerId;
    }

    /**
     * Sets the value of the newSignerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignerIdDTO }
     *     
     */
    public void setNewSignerId(SignerIdDTO value) {
        this.newSignerId = value;
    }

}
