//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.03 at 03:49:31 PM CEST 
//


package consumesoap.soapclient.stubs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for assignedModuleDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="assignedModuleDTO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://cm2.ttp.ganimed.icmvc.emau.org/}fhirIdDTO"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="defaultConsentStatus" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}consentStatus" minOccurs="0"/&gt;
 *         &lt;element name="displayCheckboxes" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}consentStatus" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="expirationProperties" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}expirationPropertiesDTO" minOccurs="0"/&gt;
 *         &lt;element name="externProperties" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mandatory" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="module" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}moduleDTO" minOccurs="0"/&gt;
 *         &lt;element name="orderNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="parent" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}moduleKeyDTO" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assignedModuleDTO", propOrder = {
    "comment",
    "defaultConsentStatus",
    "displayCheckboxes",
    "expirationProperties",
    "externProperties",
    "mandatory",
    "module",
    "orderNumber",
    "parent"
})
public class AssignedModuleDTO
    extends FhirIdDTO
{

    protected String comment;
    @XmlSchemaType(name = "string")
    protected ConsentStatus defaultConsentStatus;
    @XmlElement(nillable = true)
    @XmlSchemaType(name = "string")
    protected List<ConsentStatus> displayCheckboxes;
    protected ExpirationPropertiesDTO expirationProperties;
    protected String externProperties;
    protected boolean mandatory;
    protected ModuleDTO module;
    protected int orderNumber;
    protected ModuleKeyDTO parent;

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the defaultConsentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ConsentStatus }
     *     
     */
    public ConsentStatus getDefaultConsentStatus() {
        return defaultConsentStatus;
    }

    /**
     * Sets the value of the defaultConsentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsentStatus }
     *     
     */
    public void setDefaultConsentStatus(ConsentStatus value) {
        this.defaultConsentStatus = value;
    }

    /**
     * Gets the value of the displayCheckboxes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the displayCheckboxes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisplayCheckboxes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConsentStatus }
     * 
     * 
     */
    public List<ConsentStatus> getDisplayCheckboxes() {
        if (displayCheckboxes == null) {
            displayCheckboxes = new ArrayList<ConsentStatus>();
        }
        return this.displayCheckboxes;
    }

    /**
     * Gets the value of the expirationProperties property.
     * 
     * @return
     *     possible object is
     *     {@link ExpirationPropertiesDTO }
     *     
     */
    public ExpirationPropertiesDTO getExpirationProperties() {
        return expirationProperties;
    }

    /**
     * Sets the value of the expirationProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpirationPropertiesDTO }
     *     
     */
    public void setExpirationProperties(ExpirationPropertiesDTO value) {
        this.expirationProperties = value;
    }

    /**
     * Gets the value of the externProperties property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternProperties() {
        return externProperties;
    }

    /**
     * Sets the value of the externProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternProperties(String value) {
        this.externProperties = value;
    }

    /**
     * Gets the value of the mandatory property.
     * 
     */
    public boolean isMandatory() {
        return mandatory;
    }

    /**
     * Sets the value of the mandatory property.
     * 
     */
    public void setMandatory(boolean value) {
        this.mandatory = value;
    }

    /**
     * Gets the value of the module property.
     * 
     * @return
     *     possible object is
     *     {@link ModuleDTO }
     *     
     */
    public ModuleDTO getModule() {
        return module;
    }

    /**
     * Sets the value of the module property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModuleDTO }
     *     
     */
    public void setModule(ModuleDTO value) {
        this.module = value;
    }

    /**
     * Gets the value of the orderNumber property.
     * 
     */
    public int getOrderNumber() {
        return orderNumber;
    }

    /**
     * Sets the value of the orderNumber property.
     * 
     */
    public void setOrderNumber(int value) {
        this.orderNumber = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link ModuleKeyDTO }
     *     
     */
    public ModuleKeyDTO getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModuleKeyDTO }
     *     
     */
    public void setParent(ModuleKeyDTO value) {
        this.parent = value;
    }

}
