//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.04 at 05:15:20 PM CET 
//


package consumesoap.soapclient.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for checkConsentConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="checkConsentConfig"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="idMatchingType" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}idMatchingType" minOccurs="0"/&gt;
 *         &lt;element name="ignoreVersionNumber" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="requestDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="unknownStateIsConsideredAsDecline" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="useAliases" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "checkConsentConfig", propOrder = {
    "idMatchingType",
    "ignoreVersionNumber",
    "requestDate",
    "unknownStateIsConsideredAsDecline",
    "useAliases"
})
public class CheckConsentConfig {

    @XmlSchemaType(name = "string")
    protected IdMatchingType idMatchingType;
    protected boolean ignoreVersionNumber;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar requestDate;
    protected boolean unknownStateIsConsideredAsDecline;
    protected boolean useAliases;

    /**
     * Gets the value of the idMatchingType property.
     * 
     * @return
     *     possible object is
     *     {@link IdMatchingType }
     *     
     */
    public IdMatchingType getIdMatchingType() {
        return idMatchingType;
    }

    /**
     * Sets the value of the idMatchingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdMatchingType }
     *     
     */
    public void setIdMatchingType(IdMatchingType value) {
        this.idMatchingType = value;
    }

    /**
     * Gets the value of the ignoreVersionNumber property.
     * 
     */
    public boolean isIgnoreVersionNumber() {
        return ignoreVersionNumber;
    }

    /**
     * Sets the value of the ignoreVersionNumber property.
     * 
     */
    public void setIgnoreVersionNumber(boolean value) {
        this.ignoreVersionNumber = value;
    }

    /**
     * Gets the value of the requestDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRequestDate() {
        return requestDate;
    }

    /**
     * Sets the value of the requestDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRequestDate(XMLGregorianCalendar value) {
        this.requestDate = value;
    }

    /**
     * Gets the value of the unknownStateIsConsideredAsDecline property.
     * 
     */
    public boolean isUnknownStateIsConsideredAsDecline() {
        return unknownStateIsConsideredAsDecline;
    }

    /**
     * Sets the value of the unknownStateIsConsideredAsDecline property.
     * 
     */
    public void setUnknownStateIsConsideredAsDecline(boolean value) {
        this.unknownStateIsConsideredAsDecline = value;
    }

    /**
     * Gets the value of the useAliases property.
     * 
     */
    public boolean isUseAliases() {
        return useAliases;
    }

    /**
     * Sets the value of the useAliases property.
     * 
     */
    public void setUseAliases(boolean value) {
        this.useAliases = value;
    }

}
