//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.04 at 05:15:20 PM CET 
//


package consumesoap.soapclient.stubs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for consentTemplateType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="consentTemplateType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CONSENT"/&gt;
 *     &lt;enumeration value="REVOCATION"/&gt;
 *     &lt;enumeration value="REFUSAL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "consentTemplateType")
@XmlEnum
public enum ConsentTemplateType {

    CONSENT,
    REVOCATION,
    REFUSAL;

    public String value() {
        return name();
    }

    public static ConsentTemplateType fromValue(String v) {
        return valueOf(v);
    }

}
