//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.12 at 08:19:09 AM CEST 
//


package consumesoap.soapclient.stubs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for consentDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="consentDTO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://cm2.ttp.ganimed.icmvc.emau.org/}consentLightDTO"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="freeTextVals" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}freeTextValDTO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="patientSignatureBase64" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="physicianSignatureBase64" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="scans" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}consentScanDTO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consentDTO", propOrder = {
    "freeTextVals",
    "patientSignatureBase64",
    "physicianSignatureBase64",
    "scans"
})
public class ConsentDTO
    extends ConsentLightDTO
{

    @XmlElement(nillable = true)
    protected List<FreeTextValDTO> freeTextVals;
    protected String patientSignatureBase64;
    protected String physicianSignatureBase64;
    @XmlElement(nillable = true)
    protected List<ConsentScanDTO> scans;

    /**
     * Gets the value of the freeTextVals property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the freeTextVals property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFreeTextVals().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FreeTextValDTO }
     * 
     * 
     */
    public List<FreeTextValDTO> getFreeTextVals() {
        if (freeTextVals == null) {
            freeTextVals = new ArrayList<FreeTextValDTO>();
        }
        return this.freeTextVals;
    }

    /**
     * Gets the value of the patientSignatureBase64 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientSignatureBase64() {
        return patientSignatureBase64;
    }

    /**
     * Sets the value of the patientSignatureBase64 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientSignatureBase64(String value) {
        this.patientSignatureBase64 = value;
    }

    /**
     * Gets the value of the physicianSignatureBase64 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhysicianSignatureBase64() {
        return physicianSignatureBase64;
    }

    /**
     * Sets the value of the physicianSignatureBase64 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhysicianSignatureBase64(String value) {
        this.physicianSignatureBase64 = value;
    }

    /**
     * Gets the value of the scans property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scans property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScans().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConsentScanDTO }
     * 
     * 
     */
    public List<ConsentScanDTO> getScans() {
        if (scans == null) {
            scans = new ArrayList<ConsentScanDTO>();
        }
        return this.scans;
    }

}
