//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.04 at 05:15:20 PM CET 
//


package consumesoap.soapclient.stubs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for consentStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="consentStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ACCEPTED"/&gt;
 *     &lt;enumeration value="DECLINED"/&gt;
 *     &lt;enumeration value="UNKNOWN"/&gt;
 *     &lt;enumeration value="NOT_ASKED"/&gt;
 *     &lt;enumeration value="NOT_CHOSEN"/&gt;
 *     &lt;enumeration value="WITHDRAWN"/&gt;
 *     &lt;enumeration value="INVALIDATED"/&gt;
 *     &lt;enumeration value="REFUSED"/&gt;
 *     &lt;enumeration value="EXPIRED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "consentStatus")
@XmlEnum
public enum ConsentStatus {

    ACCEPTED,
    DECLINED,
    UNKNOWN,
    NOT_ASKED,
    NOT_CHOSEN,
    WITHDRAWN,
    INVALIDATED,
    REFUSED,
    EXPIRED;

    public String value() {
        return name();
    }

    public static ConsentStatus fromValue(String v) {
        return valueOf(v);
    }

}
