//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.12 at 08:19:09 AM CEST 
//


package consumesoap.soapclient.stubs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for consentField.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="consentField"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="NONE"/&gt;
 *     &lt;enumeration value="DATE"/&gt;
 *     &lt;enumeration value="CT_VERSION"/&gt;
 *     &lt;enumeration value="CT_NAME"/&gt;
 *     &lt;enumeration value="SIGNER_ID"/&gt;
 *     &lt;enumeration value="QC_TYPE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "consentField")
@XmlEnum
public enum ConsentField {

    NONE,
    DATE,
    CT_VERSION,
    CT_NAME,
    SIGNER_ID,
    QC_TYPE;

    public String value() {
        return name();
    }

    public static ConsentField fromValue(String v) {
        return valueOf(v);
    }

}
