//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.12 at 08:19:09 AM CEST 
//


package consumesoap.soapclient.stubs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for consentLightDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="consentLightDTO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://cm2.ttp.ganimed.icmvc.emau.org/}fhirIdDTO"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="consentDates" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}consentDateValuesDTO" minOccurs="0"/&gt;
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="expirationProperties" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}expirationPropertiesDTO" minOccurs="0"/&gt;
 *         &lt;element name="externProperties" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="key" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}consentKeyDTO" minOccurs="0"/&gt;
 *         &lt;element name="moduleStates"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="entry" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="key" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}moduleKeyDTO" minOccurs="0"/&gt;
 *                             &lt;element name="value" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}moduleStateDTO" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="patientSignatureIsFromGuardian" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="patientSigningDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="patientSigningPlace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="physicianId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="physicianSigningDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="physicianSigningPlace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="qualityControl" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}qcdto" minOccurs="0"/&gt;
 *         &lt;element name="scanFileTypes" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}fileTypeDTO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="templateType" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}consentTemplateType" minOccurs="0"/&gt;
 *         &lt;element name="updateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="validFromDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consentLightDTO", propOrder = {
    "comment",
    "consentDates",
    "creationDate",
    "expirationProperties",
    "externProperties",
    "key",
    "moduleStates",
    "patientSignatureIsFromGuardian",
    "patientSigningDate",
    "patientSigningPlace",
    "physicianId",
    "physicianSigningDate",
    "physicianSigningPlace",
    "qualityControl",
    "scanFileTypes",
    "templateType",
    "updateDate",
    "validFromDate"
})
@XmlSeeAlso({
    ConsentDTO.class
})
public class ConsentLightDTO
    extends FhirIdDTO
{

    protected String comment;
    protected ConsentDateValuesDTO consentDates;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDate;
    protected ExpirationPropertiesDTO expirationProperties;
    protected String externProperties;
    protected ConsentKeyDTO key;
    @XmlElement(required = true)
    protected ConsentLightDTO.ModuleStates moduleStates;
    protected boolean patientSignatureIsFromGuardian;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar patientSigningDate;
    protected String patientSigningPlace;
    protected String physicianId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar physicianSigningDate;
    protected String physicianSigningPlace;
    protected Qcdto qualityControl;
    @XmlElement(nillable = true)
    protected List<FileTypeDTO> scanFileTypes;
    @XmlSchemaType(name = "string")
    protected ConsentTemplateType templateType;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updateDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validFromDate;

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the consentDates property.
     * 
     * @return
     *     possible object is
     *     {@link ConsentDateValuesDTO }
     *     
     */
    public ConsentDateValuesDTO getConsentDates() {
        return consentDates;
    }

    /**
     * Sets the value of the consentDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsentDateValuesDTO }
     *     
     */
    public void setConsentDates(ConsentDateValuesDTO value) {
        this.consentDates = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the expirationProperties property.
     * 
     * @return
     *     possible object is
     *     {@link ExpirationPropertiesDTO }
     *     
     */
    public ExpirationPropertiesDTO getExpirationProperties() {
        return expirationProperties;
    }

    /**
     * Sets the value of the expirationProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpirationPropertiesDTO }
     *     
     */
    public void setExpirationProperties(ExpirationPropertiesDTO value) {
        this.expirationProperties = value;
    }

    /**
     * Gets the value of the externProperties property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternProperties() {
        return externProperties;
    }

    /**
     * Sets the value of the externProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternProperties(String value) {
        this.externProperties = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link ConsentKeyDTO }
     *     
     */
    public ConsentKeyDTO getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsentKeyDTO }
     *     
     */
    public void setKey(ConsentKeyDTO value) {
        this.key = value;
    }

    /**
     * Gets the value of the moduleStates property.
     * 
     * @return
     *     possible object is
     *     {@link ConsentLightDTO.ModuleStates }
     *     
     */
    public ConsentLightDTO.ModuleStates getModuleStates() {
        return moduleStates;
    }

    /**
     * Sets the value of the moduleStates property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsentLightDTO.ModuleStates }
     *     
     */
    public void setModuleStates(ConsentLightDTO.ModuleStates value) {
        this.moduleStates = value;
    }

    /**
     * Gets the value of the patientSignatureIsFromGuardian property.
     * 
     */
    public boolean isPatientSignatureIsFromGuardian() {
        return patientSignatureIsFromGuardian;
    }

    /**
     * Sets the value of the patientSignatureIsFromGuardian property.
     * 
     */
    public void setPatientSignatureIsFromGuardian(boolean value) {
        this.patientSignatureIsFromGuardian = value;
    }

    /**
     * Gets the value of the patientSigningDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPatientSigningDate() {
        return patientSigningDate;
    }

    /**
     * Sets the value of the patientSigningDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPatientSigningDate(XMLGregorianCalendar value) {
        this.patientSigningDate = value;
    }

    /**
     * Gets the value of the patientSigningPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientSigningPlace() {
        return patientSigningPlace;
    }

    /**
     * Sets the value of the patientSigningPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientSigningPlace(String value) {
        this.patientSigningPlace = value;
    }

    /**
     * Gets the value of the physicianId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhysicianId() {
        return physicianId;
    }

    /**
     * Sets the value of the physicianId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhysicianId(String value) {
        this.physicianId = value;
    }

    /**
     * Gets the value of the physicianSigningDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPhysicianSigningDate() {
        return physicianSigningDate;
    }

    /**
     * Sets the value of the physicianSigningDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPhysicianSigningDate(XMLGregorianCalendar value) {
        this.physicianSigningDate = value;
    }

    /**
     * Gets the value of the physicianSigningPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhysicianSigningPlace() {
        return physicianSigningPlace;
    }

    /**
     * Sets the value of the physicianSigningPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhysicianSigningPlace(String value) {
        this.physicianSigningPlace = value;
    }

    /**
     * Gets the value of the qualityControl property.
     * 
     * @return
     *     possible object is
     *     {@link Qcdto }
     *     
     */
    public Qcdto getQualityControl() {
        return qualityControl;
    }

    /**
     * Sets the value of the qualityControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Qcdto }
     *     
     */
    public void setQualityControl(Qcdto value) {
        this.qualityControl = value;
    }

    /**
     * Gets the value of the scanFileTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scanFileTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScanFileTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileTypeDTO }
     * 
     * 
     */
    public List<FileTypeDTO> getScanFileTypes() {
        if (scanFileTypes == null) {
            scanFileTypes = new ArrayList<FileTypeDTO>();
        }
        return this.scanFileTypes;
    }

    /**
     * Gets the value of the templateType property.
     * 
     * @return
     *     possible object is
     *     {@link ConsentTemplateType }
     *     
     */
    public ConsentTemplateType getTemplateType() {
        return templateType;
    }

    /**
     * Sets the value of the templateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsentTemplateType }
     *     
     */
    public void setTemplateType(ConsentTemplateType value) {
        this.templateType = value;
    }

    /**
     * Gets the value of the updateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdateDate() {
        return updateDate;
    }

    /**
     * Sets the value of the updateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdateDate(XMLGregorianCalendar value) {
        this.updateDate = value;
    }

    /**
     * Gets the value of the validFromDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidFromDate() {
        return validFromDate;
    }

    /**
     * Sets the value of the validFromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidFromDate(XMLGregorianCalendar value) {
        this.validFromDate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="entry" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="key" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}moduleKeyDTO" minOccurs="0"/&gt;
     *                   &lt;element name="value" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}moduleStateDTO" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entry"
    })
    public static class ModuleStates {

        protected List<ConsentLightDTO.ModuleStates.Entry> entry;

        /**
         * Gets the value of the entry property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entry property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ConsentLightDTO.ModuleStates.Entry }
         * 
         * 
         */
        public List<ConsentLightDTO.ModuleStates.Entry> getEntry() {
            if (entry == null) {
                entry = new ArrayList<ConsentLightDTO.ModuleStates.Entry>();
            }
            return this.entry;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="key" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}moduleKeyDTO" minOccurs="0"/&gt;
         *         &lt;element name="value" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}moduleStateDTO" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "key",
            "value"
        })
        public static class Entry {

            protected ModuleKeyDTO key;
            protected ModuleStateDTO value;

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link ModuleKeyDTO }
             *     
             */
            public ModuleKeyDTO getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link ModuleKeyDTO }
             *     
             */
            public void setKey(ModuleKeyDTO value) {
                this.key = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link ModuleStateDTO }
             *     
             */
            public ModuleStateDTO getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link ModuleStateDTO }
             *     
             */
            public void setValue(ModuleStateDTO value) {
                this.value = value;
            }

        }

    }

}
