//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.03 at 03:49:31 PM CEST 
//


package consumesoap.soapclient.stubs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for consentTemplateStructureDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="consentTemplateStructureDTO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="children"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="entry" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="key" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}moduleKeyDTO" minOccurs="0"/&gt;
 *                             &lt;element name="value" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}moduleKeyDTOArray" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="firstLevelModules" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}moduleKeyDTO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consentTemplateStructureDTO", propOrder = {
    "children",
    "firstLevelModules"
})
public class ConsentTemplateStructureDTO {

    @XmlElement(required = true)
    protected ConsentTemplateStructureDTO.Children children;
    @XmlElement(nillable = true)
    protected List<ModuleKeyDTO> firstLevelModules;

    /**
     * Gets the value of the children property.
     * 
     * @return
     *     possible object is
     *     {@link ConsentTemplateStructureDTO.Children }
     *     
     */
    public ConsentTemplateStructureDTO.Children getChildren() {
        return children;
    }

    /**
     * Sets the value of the children property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsentTemplateStructureDTO.Children }
     *     
     */
    public void setChildren(ConsentTemplateStructureDTO.Children value) {
        this.children = value;
    }

    /**
     * Gets the value of the firstLevelModules property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the firstLevelModules property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFirstLevelModules().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModuleKeyDTO }
     * 
     * 
     */
    public List<ModuleKeyDTO> getFirstLevelModules() {
        if (firstLevelModules == null) {
            firstLevelModules = new ArrayList<ModuleKeyDTO>();
        }
        return this.firstLevelModules;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="entry" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="key" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}moduleKeyDTO" minOccurs="0"/&gt;
     *                   &lt;element name="value" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}moduleKeyDTOArray" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entry"
    })
    public static class Children {

        protected List<ConsentTemplateStructureDTO.Children.Entry> entry;

        /**
         * Gets the value of the entry property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entry property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ConsentTemplateStructureDTO.Children.Entry }
         * 
         * 
         */
        public List<ConsentTemplateStructureDTO.Children.Entry> getEntry() {
            if (entry == null) {
                entry = new ArrayList<ConsentTemplateStructureDTO.Children.Entry>();
            }
            return this.entry;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="key" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}moduleKeyDTO" minOccurs="0"/&gt;
         *         &lt;element name="value" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}moduleKeyDTOArray" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "key",
            "value"
        })
        public static class Entry {

            protected ModuleKeyDTO key;
            protected ModuleKeyDTOArray value;

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link ModuleKeyDTO }
             *     
             */
            public ModuleKeyDTO getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link ModuleKeyDTO }
             *     
             */
            public void setKey(ModuleKeyDTO value) {
                this.key = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link ModuleKeyDTOArray }
             *     
             */
            public ModuleKeyDTOArray getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link ModuleKeyDTOArray }
             *     
             */
            public void setValue(ModuleKeyDTOArray value) {
                this.value = value;
            }

        }

    }

}
