//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.12 at 08:19:09 AM CEST 
//


package consumesoap.soapclient.stubs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for domainDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="domainDTO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://cm2.ttp.ganimed.icmvc.emau.org/}fhirIdDTO"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="ctVersionConverter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="expirationProperties" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}expirationPropertiesDTO" minOccurs="0"/&gt;
 *         &lt;element name="externProperties" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="finalised" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="logo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="moduleVersionConverter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="policyVersionConverter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="properties" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="signerIdTypes" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="updateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "domainDTO", propOrder = {
    "comment",
    "creationDate",
    "ctVersionConverter",
    "expirationProperties",
    "externProperties",
    "finalised",
    "label",
    "logo",
    "moduleVersionConverter",
    "name",
    "policyVersionConverter",
    "properties",
    "signerIdTypes",
    "updateDate"
})
public class DomainDTO
    extends FhirIdDTO
{

    protected String comment;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDate;
    protected String ctVersionConverter;
    protected ExpirationPropertiesDTO expirationProperties;
    protected String externProperties;
    protected boolean finalised;
    protected String label;
    protected String logo;
    protected String moduleVersionConverter;
    protected String name;
    protected String policyVersionConverter;
    protected String properties;
    @XmlElement(nillable = true)
    protected List<String> signerIdTypes;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updateDate;

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the ctVersionConverter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtVersionConverter() {
        return ctVersionConverter;
    }

    /**
     * Sets the value of the ctVersionConverter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtVersionConverter(String value) {
        this.ctVersionConverter = value;
    }

    /**
     * Gets the value of the expirationProperties property.
     * 
     * @return
     *     possible object is
     *     {@link ExpirationPropertiesDTO }
     *     
     */
    public ExpirationPropertiesDTO getExpirationProperties() {
        return expirationProperties;
    }

    /**
     * Sets the value of the expirationProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpirationPropertiesDTO }
     *     
     */
    public void setExpirationProperties(ExpirationPropertiesDTO value) {
        this.expirationProperties = value;
    }

    /**
     * Gets the value of the externProperties property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternProperties() {
        return externProperties;
    }

    /**
     * Sets the value of the externProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternProperties(String value) {
        this.externProperties = value;
    }

    /**
     * Gets the value of the finalised property.
     * 
     */
    public boolean isFinalised() {
        return finalised;
    }

    /**
     * Sets the value of the finalised property.
     * 
     */
    public void setFinalised(boolean value) {
        this.finalised = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the logo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogo() {
        return logo;
    }

    /**
     * Sets the value of the logo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogo(String value) {
        this.logo = value;
    }

    /**
     * Gets the value of the moduleVersionConverter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModuleVersionConverter() {
        return moduleVersionConverter;
    }

    /**
     * Sets the value of the moduleVersionConverter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModuleVersionConverter(String value) {
        this.moduleVersionConverter = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the policyVersionConverter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyVersionConverter() {
        return policyVersionConverter;
    }

    /**
     * Sets the value of the policyVersionConverter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyVersionConverter(String value) {
        this.policyVersionConverter = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProperties(String value) {
        this.properties = value;
    }

    /**
     * Gets the value of the signerIdTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signerIdTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignerIdTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSignerIdTypes() {
        if (signerIdTypes == null) {
            signerIdTypes = new ArrayList<String>();
        }
        return this.signerIdTypes;
    }

    /**
     * Gets the value of the updateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdateDate() {
        return updateDate;
    }

    /**
     * Sets the value of the updateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdateDate(XMLGregorianCalendar value) {
        this.updateDate = value;
    }

}
