//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.03 at 03:49:31 PM CEST 
//


package consumesoap.soapclient.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for finaliseModule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="finaliseModule"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="moduleKey" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}moduleKeyDTO"/&gt;
 *         &lt;element name="finaliseRelatedEntities" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "finaliseModule", propOrder = {
    "moduleKey",
    "finaliseRelatedEntities"
})
public class FinaliseModule {

    @XmlElement(required = true)
    protected ModuleKeyDTO moduleKey;
    protected boolean finaliseRelatedEntities;

    /**
     * Gets the value of the moduleKey property.
     * 
     * @return
     *     possible object is
     *     {@link ModuleKeyDTO }
     *     
     */
    public ModuleKeyDTO getModuleKey() {
        return moduleKey;
    }

    /**
     * Sets the value of the moduleKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModuleKeyDTO }
     *     
     */
    public void setModuleKey(ModuleKeyDTO value) {
        this.moduleKey = value;
    }

    /**
     * Gets the value of the finaliseRelatedEntities property.
     * 
     */
    public boolean isFinaliseRelatedEntities() {
        return finaliseRelatedEntities;
    }

    /**
     * Sets the value of the finaliseRelatedEntities property.
     * 
     */
    public void setFinaliseRelatedEntities(boolean value) {
        this.finaliseRelatedEntities = value;
    }

}
