//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.12 at 08:19:09 AM CEST 
//


package consumesoap.soapclient.stubs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for idMatchingType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="idMatchingType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AT_LEAST_ONE"/&gt;
 *     &lt;enumeration value="AT_LEAST_ALL"/&gt;
 *     &lt;enumeration value="EXACT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "idMatchingType")
@XmlEnum
public enum IdMatchingType {

    AT_LEAST_ONE,
    AT_LEAST_ALL,
    EXACT;

    public String value() {
        return name();
    }

    public static IdMatchingType fromValue(String v) {
        return valueOf(v);
    }

}
