//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.03 at 03:49:31 PM CEST 
//


package consumesoap.soapclient.stubs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for moduleStateDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="moduleStateDTO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="consentState" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}consentStatus" minOccurs="0"/&gt;
 *         &lt;element name="key" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}moduleKeyDTO" minOccurs="0"/&gt;
 *         &lt;element name="policyKeys" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}policyKeyDTO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "moduleStateDTO", propOrder = {
    "consentState",
    "key",
    "policyKeys"
})
public class ModuleStateDTO {

    @XmlSchemaType(name = "string")
    protected ConsentStatus consentState;
    protected ModuleKeyDTO key;
    @XmlElement(nillable = true)
    protected List<PolicyKeyDTO> policyKeys;

    /**
     * Gets the value of the consentState property.
     * 
     * @return
     *     possible object is
     *     {@link ConsentStatus }
     *     
     */
    public ConsentStatus getConsentState() {
        return consentState;
    }

    /**
     * Sets the value of the consentState property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsentStatus }
     *     
     */
    public void setConsentState(ConsentStatus value) {
        this.consentState = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link ModuleKeyDTO }
     *     
     */
    public ModuleKeyDTO getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModuleKeyDTO }
     *     
     */
    public void setKey(ModuleKeyDTO value) {
        this.key = value;
    }

    /**
     * Gets the value of the policyKeys property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the policyKeys property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPolicyKeys().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PolicyKeyDTO }
     * 
     * 
     */
    public List<PolicyKeyDTO> getPolicyKeys() {
        if (policyKeys == null) {
            policyKeys = new ArrayList<PolicyKeyDTO>();
        }
        return this.policyKeys;
    }

}
