//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.04 at 05:15:20 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cm2.ttp.ganimed.icmvc.emau.org/")
package consumesoap.soapclient.stubs;
