//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.04 at 05:15:20 PM CET 
//


package consumesoap.soapclient.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for updateConsentTemplateInUse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateConsentTemplateInUse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="consentTemplate" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}consentTemplateDTO"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateConsentTemplateInUse", propOrder = {
    "consentTemplate"
})
public class UpdateConsentTemplateInUse {

    @XmlElement(required = true)
    protected ConsentTemplateDTO consentTemplate;

    /**
     * Gets the value of the consentTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link ConsentTemplateDTO }
     *     
     */
    public ConsentTemplateDTO getConsentTemplate() {
        return consentTemplate;
    }

    /**
     * Sets the value of the consentTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsentTemplateDTO }
     *     
     */
    public void setConsentTemplate(ConsentTemplateDTO value) {
        this.consentTemplate = value;
    }

}
