//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.04 at 05:15:20 PM CET 
//


package consumesoap.soapclient.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for validateConsent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="validateConsent"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="consent" type="{http://cm2.ttp.ganimed.icmvc.emau.org/}consentDTO"/&gt;
 *         &lt;element name="allowRevoke" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "validateConsent", propOrder = {
    "consent",
    "allowRevoke"
})
public class ValidateConsent {

    @XmlElement(required = true)
    protected ConsentDTO consent;
    protected boolean allowRevoke;

    /**
     * Gets the value of the consent property.
     * 
     * @return
     *     possible object is
     *     {@link ConsentDTO }
     *     
     */
    public ConsentDTO getConsent() {
        return consent;
    }

    /**
     * Sets the value of the consent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsentDTO }
     *     
     */
    public void setConsent(ConsentDTO value) {
        this.consent = value;
    }

    /**
     * Gets the value of the allowRevoke property.
     * 
     */
    public boolean isAllowRevoke() {
        return allowRevoke;
    }

    /**
     * Sets the value of the allowRevoke property.
     * 
     */
    public void setAllowRevoke(boolean value) {
        this.allowRevoke = value;
    }

}
